apiVersion: v1
kind: Service
metadata:
  name: rotating-proxy
spec:
  selector:
    app: rotating-proxy
  ports:
    - protocol: TCP
      port: 5566
      targetPort: 5566
    - protocol: TCP
      port: 4444
      targetPort: 4444
  type: ClusterIP
